---
AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to Create Fargate Service for Apps

Parameters:
  TargetGroupServiceArn:
    Type: String
  TaskDefServiceArn:
    Type: String
  FargateClusterArn:
    Type: String
  PublicSubnets:
    Description: Choose the PublicSubnets
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroup:
    Description: Select the Security Group
    Type: AWS::EC2::SecurityGroup::Id
  StackName:
    Type: String
  Service:
    Type: String
    
Resources:
  FargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: FargateClusterArn
      TaskDefinition:
        Ref: TaskDefServiceArn
      DesiredCount: 2
      LoadBalancers:
      - TargetGroupArn:
          Ref: TargetGroupServiceArn
        ContainerPort: 8080
        ContainerName: !Sub ${Service}-${StackName}
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref PublicSubnets
          SecurityGroups: 
            - !Ref SecurityGroup
      LaunchType: FARGATE

