---
AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create IAM Settings.

Resources:
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"

  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

Outputs:
  EcsTaskRoleArn:
    Description: ARN of ECS Task Role
    Value:
      Fn::GetAtt:
        - EcsTaskRole
        - Arn

  EcsTaskExecutionRoleArn:
    Description: ARN of ECS Task Execution Role
    Value:
      Fn::GetAtt:
        - EcsTaskExecutionRole
        - Arn

