---
AWSTemplateFormatVersion: '2010-09-09'
Description: Main Template For X-Ray Fargate Study

Parameters:
  VpcId:
    Description: ID of VPC
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Description: Choose which subnets the Network Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
  FargateClusterName:
    Type: String
    Default: fargate

Resources:
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/xray-fargate-study/sg.yaml
      Parameters:
        VpcId: !Ref VpcId

  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/xray-fargate-study/iam.yaml

  AlbServiceAStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/xray-fargate-study/alb.yaml
      Parameters:
        VpcId: !Ref VpcId
        PublicSubnets: !Join [ ",", !Ref PublicSubnets ]
        SecurityGroup: !GetAtt SecurityGroupStack.Outputs.SecurityGroupArn
        Service: service-a
        StackName: !Ref AWS::StackName

  AlbServiceBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/xray-fargate-study/alb.yaml
      Parameters:
        VpcId: !Ref VpcId
        PublicSubnets: !Join [ ",", !Ref PublicSubnets ]
        SecurityGroup: !GetAtt SecurityGroupStack.Outputs.SecurityGroupArn
        Service: service-b
        StackName: !Ref AWS::StackName

  TaskDefServiceAStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/xray-fargate-study/task-def.yaml
      Parameters:
        EcsTaskExecutionRoleArn: !GetAtt IamStack.Outputs.EcsTaskExecutionRoleArn
        EcsTaskRoleArn: !GetAtt IamStack.Outputs.EcsTaskRoleArn
        Service: service-a
        StackName: !Ref AWS::StackName
        AlbServiceDns: !GetAtt AlbServiceBStack.Outputs.LoadBalancerDns

  TaskDefServiceBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/xray-fargate-study/task-def.yaml
      Parameters:
        EcsTaskExecutionRoleArn: !GetAtt IamStack.Outputs.EcsTaskExecutionRoleArn
        EcsTaskRoleArn: !GetAtt IamStack.Outputs.EcsTaskRoleArn
        Service: service-b
        StackName: !Ref AWS::StackName
        AlbServiceDns: !GetAtt AlbServiceAStack.Outputs.LoadBalancerDns

  FargateServiceAStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/xray-fargate-study/fargate.yaml
      Parameters:
        TargetGroupServiceArn: !GetAtt AlbServiceAStack.Outputs.TargetGroupArn
        TaskDefServiceArn: !GetAtt TaskDefServiceAStack.Outputs.DefService
        FargateClusterArn: 
          !Join
          - ":"
          - - "arn"
            - "aws"
            - "ecs"
            - !Ref "AWS::Region"
            - !Ref "AWS::AccountId"
            - !Sub cluster/${FargateClusterName}
        PublicSubnets: !Join [ ",", !Ref PublicSubnets ]
        SecurityGroup: !GetAtt SecurityGroupStack.Outputs.SecurityGroupArn
        Service: service-a
        StackName: !Ref AWS::StackName

  FargateServiceBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cfn-template-group.s3.amazonaws.com/xray-fargate-study/fargate.yaml
      Parameters:
        TargetGroupServiceArn: !GetAtt AlbServiceBStack.Outputs.TargetGroupArn
        TaskDefServiceArn: !GetAtt TaskDefServiceBStack.Outputs.DefService
        FargateClusterArn: 
          !Join
          - ":"
          - - "arn"
            - "aws"
            - "ecs"
            - !Ref "AWS::Region"
            - !Ref "AWS::AccountId"
            - !Sub cluster/${FargateClusterName}
        PublicSubnets: !Join [ ",", !Ref PublicSubnets ]
        SecurityGroup: !GetAtt SecurityGroupStack.Outputs.SecurityGroupArn
        Service: service-b
        StackName: !Ref AWS::StackName